---
title: "Recent Talks"
---

<style>
.talks-page {
  max-width: 900px;
  margin: 40px auto;
  padding: 0 20px;
}

.timeline {
  position: relative;
  padding-left: 120px;
}

.timeline::before {
  content: '';
  position: absolute;
  left: 117px;
  top: 0;
  bottom: 0;
  width: 3px;
  background: linear-gradient(to bottom, #238A8D, #BFD7B5);
}

.timeline-year {
  position: relative;
  margin-bottom: 0;
}

.year-label {
  position: absolute;
  left: -120px;
  width: 106px;
  text-align: right;
  font-size: 2.4rem;
  font-weight: 700;
  color: #238A8D;
  line-height: 1;
  padding-top: 4px;
}


.year-label::after {
  content: '';
  position: absolute;
  right: -21px;
  top: 7px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #238A8D;
  border: 3px solid white;
  box-shadow: 0 0 0 2px #238A8D;
}

.year-talks {
  padding: 0 0 30px 24px;
  margin: 0;
  list-style: none;
}

.year-talks li {
  position: relative;
  padding: 12px 16px;
  margin-bottom: 10px;
  border-left: 3px solid #BFD7B5;
  background: #f9f9f9;
  border-radius: 0 6px 6px 0;
  font-size: 2rem;
  line-height: 1.7;
  transition: border-color 0.2s, background 0.2s;
}

.year-talks li:hover {
  border-left-color: #238A8D;
  background: #f0f7f7;
}

.video-container {
  margin: 10px 0 16px 24px;
  padding: 10px 14px;
  background: #f9f9f9;
  border-left: 3px solid #BFD7B5;
  border-radius: 0 6px 6px 0;
}

.video-container iframe {
  display: block;
  max-width: 100%;
}
</style>

<div class="talks-page">

<div class="timeline">

<div class="timeline-year">
<div class="year-label">2024</div>
<ul class="year-talks">

<li><a href="https://docs.google.com/presentation/d/1GpwNqoEYbDK2xN_u4WoOFJAB9mDBCuOhhXu0NzsBy18/edit?usp=sharing">Exploring initiatives to promote more comprehensive data science and statistical education</a>. <a href="https://stat.utexas.edu/">The University of Texas at Austin, Department of Statistics and Data Sciences</a>. Austin, Texas, USA.</li>

</ul>
</div>

<div class="timeline-year">
<div class="year-label">2023</div>
<ul class="year-talks">

<li>Problem-forward Statistics and Data Science to Improve Human Health. Myrto Lefkopoulou Distinguished Lectureship. Harvard T. H. Chan School of Public Health. (<a href="https://www.hsph.harvard.edu/biostatistics/myrto-award/">link</a>). Hicks, Stephanie. 2023 Sept 21. Boston, MA. USA.</li>

<li><a href="https://docs.google.com/presentation/d/1ydwawEhVnJoIqr4wejmxEcwU5O2ba7SvQq2B_WlR628/edit?usp=sharing">Reimagining Research Training Through Holistic Data Science Education</a>. <a href="https://www.biostat.washington.edu/">University of Washington Department of Biostatistics Seminar</a>. Wright, Carrie. 2023 May 4th. Seattle, WA. USA. (Virtual).</li>

</ul>
</div>

<div class="timeline-year">
<div class="year-label">2022</div>
<ul class="year-talks">

<li><a href="https://docs.google.com/presentation/d/1rN1oNZ-On4vuPanktF-HVQcS_Fr3mSqKu6pcxfwsgJI/edit?usp=sharing">Case studies to community engagement: Bringing hands-on data science experiences to the classroom</a>. <a href="https://www.icsa.org/">International Chinese Statistical Association (ICSA)</a>. Wright, Carrie. 2022 June 20th. Gainesville, Florida.</li>

</ul>
</div>

<div class="timeline-year">
<div class="year-label">2021</div>
<ul class="year-talks">

<li><a href="https://docs.google.com/presentation/d/1ueWL8XDlifDTsPlAG8lhPx37zzm1YlGKeaNu6gf8CXk/edit?usp=sharing">Addressing Open Challenges in Data Science Education</a>. Hicks, Stephanie. Department of Statistics, University of British Columbia. 2021 Feb 9. Vancouver, BC. Canada. (Virtual).</li>

</ul>
</div>

<div class="timeline-year">
<div class="year-label">2020</div>
<ul class="year-talks">

<li><a href="https://docs.google.com/presentation/d/18jymRcaW2eh6cNmN6HbazaTg8OJFToQ28kvIpeN4CGg/edit?usp=sharing">Open Case Studies</a>. Hicks, Stephanie and Wright, Carrie. <a href="https://americanhealth.jhu.edu/2020-bloomberg-american-health-summit">Bloomberg American Health Summit 2020</a>. 2020 Dec 9. Baltimore, MD. USA. (Virtual).</li>

</ul>

<div class="video-container">
<iframe width="560" height="315" src="https://www.youtube.com/embed/T1B5q6jdP6U" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<ul class="year-talks">

<li><a href="https://docs.google.com/presentation/d/1wSuRsSwI-uEyiPqtXEW12CBwr5qULK6zO7aPHsUH8T8/edit?usp=sharing">Communicating statistics and data science to the masses via Open Case Studies.</a> Hicks, Stephanie. <a href="https://ww2.amstat.org/meetings/jsm/2020/">Joint Statistical Meetings.</a> 2020 Aug 1-6. Philadelphia, PA, USA. (Virtual due to COVID-19).</li>

<li><a href="https://docs.google.com/presentation/d/10lRcBMdZ_lzWWCW46t1rThJ1kVm7Ip0Yx3UIdicUEAg/edit?usp=sharing">Addressing Real-World Challenges through Data Science Education</a>. Hicks, Stephanie. <a href="https://alliance4datascience.ai/get-involved/projects-working-groups/#active-groups">Academic Data Science Alliance (ADSA) Data Science Education special interest group (SIG)</a>. 2020 Jul 2.</li>

</ul>
</div>

<div class="timeline-year">
<div class="year-label">2019</div>
<ul class="year-talks">

<li><a href="https://docs.google.com/presentation/d/1emK1ORCmRaJLYDYwWPGhaqNRY2D8cdem_EIFmCmqS00/edit?usp=sharing">Addressing Public Health Challenges through Data Science Education</a>. Hicks, Stephanie. <a href="https://www.apha.org/annualmeeting">American Public Health Association Annual Meeting</a>. 2019 Nov 2-6. Philadelphia, PA, USA.</li>

<li>Motivating Data Science through Case Studies in Public Health. <a href="https://www.enar.org">Eastern North American Region (ENAR) Meeting of the International Biometric Society</a>. Jager, Leah. 2019 March 27. Philadelphia, PA, USA.</li>

</ul>
</div>

</div>
</div>
